### ISSUE TITLE
"demo:app" and "demo:server" are unclear

### ISSUE THREAD

**Issue by pablopaul** [codeceptjs/create-codeceptjs#7]
Whats the idea of both commands? I cant understand from the help text, please clarify.

**Comment by DavertMik** [comment]
demo app - starts CodeceptUI for a demo application

maybe we should just replace it with "demo:open" ?

**Comment by pablopaul** [comment]
How about `demo:ui`?

What is the general usage für CodeceptUI webserver mode?

**Comment by DavertMik** [comment]
removed demo-server
I think `codecept:app` is ok
